# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='song',
            table='song',
        ),
    ]
